### PR TITLE
#167750049 Deploy the base application to Heroku

### PR DESCRIPTION
**Pull request by feobaby**
**What does this PR do?**
This PR deploys the base app to heroku.

**Description of tasks to be completed?**
- add a Procfile to add the start so that heroku will pick it up

**How should this be manually tested?**
Using this link:
https://barefootnomad10-staging.herokuapp.com/
Test for an endpoint, - 
https://barefootnomad10-staging.herokuapp.com/api/v1/users/signup

**Any background context you want to provide?**
This particular deployment is for the staging environment.

**What are the relevant pivotal tracker stories?**
<a href = "https://www.pivotaltracker.com/story/show/167750049">167750045</a>

### CODE REVIEW

**Review by eokwukwe — COMMENTED** [review]
@funmi5 your PR does not contain the link of the app on Heroku.

**Review by oyewoas — APPROVED** [review]
nice @funmi5 , it works, welldone.

**Comment by darasimiolaifa** [comment]
Hi Funmi. Well done. May I ask why the only available app is the `staging`? What happened to the creation of the `production` app? Also, are `review apps` working yet? Thanks.

**Comment by feobaby** [comment]
> Hi Funmi. Well done. May I ask why the only available app is the `staging`? What happened to the creation of the `production` app? Also, are `review apps` working yet? Thanks.

Hi Darasimi, you are right, however I don't have that admin power anymore because I transferred the ownership of app to the TTL, he'll definitely set the pipelines from his side. Thanks.

**Pull request merged**
