### PR TITLE
#167750041 Integrate HoundCI with badge attached to readme

### PR DESCRIPTION
**Pull request by torsami77**
#### Description of Task to be completed?
- This is to automatically validate the codebase with standard style guides

 #### How should this be manually tested?
 #### Any background context you want to provide?
- Technically HoundCI has no official readme badge, the https://shields.io service was used to generate a representive markdown badge for the readme

 #### What are the relevant pivotal tracker stories?
#167750041 

 #### Screenshots (if appropriate)
 #### Questions:

### CODE REVIEW

**Review by eokwukwe — CHANGES_REQUESTED** [review]
Good job so far @torsami77. Please, you need to edit your commit message. Review the `wiki` and confirm that your footer is correct and that the letter casing used in your commit message and body is correct.

**Comment by torsami77** [comment]
Thanks for the feedback, another question I have is to know if abbreviations should also be lowered case, in this scenario 'Continuous Integration' as in houndCI or should it be formatted as houndci?

**Review by eokwukwe — DISMISSED** [review]

**Review by feobaby — APPROVED** [review]
Good Job Samson, I am satisfied with the configuration, _please watch out for proper commit messages next time._

**Review by oyewoas — APPROVED** [review]
Nice one, but you can check the wiki for the proper commit messages, for subsequent commits.

**Pull request merged**
